window.__ITEMS_DATA__ = [
  // === Berry ===
  { name: "Berry Juice", category: "Berry" },
  { name: "Ganlon Berry", category: "Berry" },
  { name: "Leppa Berry", category: "Berry" },
  { name: "Liechi Berry", category: "Berry" },
  { name: "Lum Berry", category: "Berry" },
  { name: "Oran Berry", category: "Berry" },
  { name: "Petaya Berry", category: "Berry" },
  { name: "Salac Berry", category: "Berry" },
  { name: "Sitrus Berry", category: "Berry" },
  { name: "Starf Berry", category: "Berry" },

  // === Choice ===
  { name: "Choice Band", category: "Choice" },
  { name: "Choice Scarf", category: "Choice" },
  { name: "Choice Specs", category: "Choice" },

  // === Type Boost ===
  { name: "Black Belt", category: "Type Boost" },
  { name: "Black Glasses", category: "Type Boost" },
  { name: "Charcoal", category: "Type Boost" },
  { name: "Dragon Fang", category: "Type Boost" },
  { name: "Hard Stone", category: "Type Boost" },
  { name: "Magnet", category: "Type Boost" },
  { name: "Miracle Seed", category: "Type Boost" },
  { name: "Mystic Water", category: "Type Boost" },
  { name: "Never-Melt Ice", category: "Type Boost" },
  { name: "Poison Barb", category: "Type Boost" },
  { name: "Sharp Beak", category: "Type Boost" },
  { name: "Silk Scarf", category: "Type Boost" },
  { name: "Silver Powder", category: "Type Boost" },
  { name: "Soft Sand", category: "Type Boost" },
  { name: "Spell Tag", category: "Type Boost" },
  { name: "Twisted Spoon", category: "Type Boost" },

  // === Evolution ===
  { name: "Everstone", category: "Evolution" },
  { name: "King's Rock", category: "Evolution" },
  { name: "Metal Coat", category: "Evolution" },
  { name: "Razor Claw", category: "Evolution" },
  { name: "Razor Fang", category: "Evolution" },
  { name: "Up-Grade", category: "Evolution" },
  { name: "Dubious Disc", category: "Evolution" },
  { name: "Reaper Cloth", category: "Evolution" },
  { name: "Electirizer", category: "Evolution" },
  { name: "Magmarizer", category: "Evolution" },
  { name: "Protector", category: "Evolution" },
  { name: "Oval Stone", category: "Evolution" },
  { name: "Prism Scale", category: "Evolution" },
  { name: "Sachet", category: "Evolution" },
  { name: "Whipped Dream", category: "Evolution" },
  { name: "Ice Stone", category: "Evolution" },
  { name: "Fire Stone", category: "Evolution" },
  { name: "Thunder Stone", category: "Evolution" },
  { name: "Water Stone", category: "Evolution" },
  { name: "Leaf Stone", category: "Evolution" },
  { name: "Moon Stone", category: "Evolution" },
  { name: "Sun Stone", category: "Evolution" },
  { name: "Shiny Stone", category: "Evolution" },
  { name: "Dusk Stone", category: "Evolution" },
  { name: "Dawn Stone", category: "Evolution" },

  // === Battle ===
  { name: "Absorb Bulb", category: "Battle" },
  { name: "Adrenaline Orb", category: "Battle" },
  { name: "Air Balloon", category: "Battle" },
  { name: "Assault Vest", category: "Battle" },
  { name: "Big Root", category: "Battle" },
  { name: "Binding Band", category: "Battle" },
  { name: "Black Sludge", category: "Battle" },
  { name: "Blunder Policy", category: "Battle" },
  { name: "Booster Energy", category: "Battle" },
  { name: "Bright Powder", category: "Battle" },
  { name: "Cell Battery", category: "Battle" },
  { name: "Clear Amulet", category: "Battle" },
  { name: "Covert Cloak", category: "Battle" },
  { name: "Damp Rock", category: "Battle" },
  { name: "Destiny Knot", category: "Battle" },
  { name: "Eject Button", category: "Battle" },
  { name: "Eject Pack", category: "Battle" },
  { name: "Electric Seed", category: "Battle" },
  { name: "Eviolite", category: "Battle" },
  { name: "Expert Belt", category: "Battle" },
  { name: "Flame Orb", category: "Battle" },
  { name: "Float Stone", category: "Battle" },
  { name: "Focus Band", category: "Battle" },
  { name: "Focus Sash", category: "Battle" },
  { name: "Grassy Seed", category: "Battle" },
  { name: "Grip Claw", category: "Battle" },
  { name: "Heat Rock", category: "Battle" },
  { name: "Heavy-Duty Boots", category: "Battle" },
  { name: "Icy Rock", category: "Battle" },
  { name: "Iron Ball", category: "Battle" },
  { name: "Lagging Tail", category: "Battle" },
  { name: "Life Orb", category: "Battle" },
  { name: "Light Clay", category: "Battle" },
  { name: "Loaded Dice", category: "Battle" },
  { name: "Luminous Moss", category: "Battle" },
  { name: "Mental Herb", category: "Battle" },
  { name: "Metronome", category: "Battle" },
  { name: "Mirror Herb", category: "Battle" },
  { name: "Misty Seed", category: "Battle" },
  { name: "Muscle Band", category: "Battle" },
  { name: "Power Herb", category: "Battle" },
  { name: "Psychic Seed", category: "Battle" },
  { name: "Punching Glove", category: "Battle" },
  { name: "Quick Claw", category: "Battle" },
  { name: "Red Card", category: "Battle" },
  { name: "Rocky Helmet", category: "Battle" },
  { name: "Room Service", category: "Battle" },
  { name: "Safety Goggles", category: "Battle" },
  { name: "Scope Lens", category: "Battle" },
  { name: "Shed Shell", category: "Battle" },
  { name: "Smoke Ball", category: "Battle" },
  { name: "Smooth Rock", category: "Battle" },
  { name: "Snowball", category: "Battle" },
  { name: "Sticky Barb", category: "Battle" },
  { name: "Terrain Extender", category: "Battle" },
  { name: "Throat Spray", category: "Battle" },
  { name: "Toxic Orb", category: "Battle" },
  { name: "Utility Umbrella", category: "Battle" },
  { name: "White Herb", category: "Battle" },
  { name: "Wide Lens", category: "Battle" },
  { name: "Wise Glasses", category: "Battle" },
  { name: "Zoom Lens", category: "Battle" },

  // === Mega Stone ===
  { name: "Absolite", category: "Mega Stone" },
  { name: "Aggronite", category: "Mega Stone" },
  { name: "Alakazite", category: "Mega Stone" },
  { name: "Altarianite", category: "Mega Stone" },
  { name: "Ampharosite", category: "Mega Stone" },
  { name: "Audinite", category: "Mega Stone" },
  { name: "Banettite", category: "Mega Stone" },
  { name: "Beedrillite", category: "Mega Stone" },
  { name: "Blastoisinite", category: "Mega Stone" },
  { name: "Blazikenite", category: "Mega Stone" },
  { name: "Cameruptite", category: "Mega Stone" },
  { name: "Charizardite X", category: "Mega Stone" },
  { name: "Charizardite Y", category: "Mega Stone" },
  { name: "Diancite", category: "Mega Stone" },
  { name: "Galladite", category: "Mega Stone" },
  { name: "Garchompite", category: "Mega Stone" },
  { name: "Gardevoirite", category: "Mega Stone" },
  { name: "Gengarite", category: "Mega Stone" },
  { name: "Glalitite", category: "Mega Stone" },
  { name: "Gyaradosite", category: "Mega Stone" },
  { name: "Heracronite", category: "Mega Stone" },
  { name: "Houndoominite", category: "Mega Stone" },
  { name: "Kangaskhanite", category: "Mega Stone" },
  { name: "Latiasite", category: "Mega Stone" },
  { name: "Latiosite", category: "Mega Stone" },
  { name: "Lopunnite", category: "Mega Stone" },
  { name: "Lucarionite", category: "Mega Stone" },
  { name: "Manectite", category: "Mega Stone" },
  { name: "Mawilite", category: "Mega Stone" },
  { name: "Medichamite", category: "Mega Stone" },
  { name: "Metagrossite", category: "Mega Stone" },
  { name: "Mewtwonite X", category: "Mega Stone" },
  { name: "Mewtwonite Y", category: "Mega Stone" },
  { name: "Pidgeotite", category: "Mega Stone" },
  { name: "Pinsirite", category: "Mega Stone" },
  { name: "Sablenite", category: "Mega Stone" },
  { name: "Salamencite", category: "Mega Stone" },
  { name: "Sceptilite", category: "Mega Stone" },
  { name: "Scizorite", category: "Mega Stone" },
  { name: "Sharpedonite", category: "Mega Stone" },
  { name: "Slowbronite", category: "Mega Stone" },
  { name: "Steelixite", category: "Mega Stone" },
  { name: "Swampertite", category: "Mega Stone" },
  { name: "Tyranitarite", category: "Mega Stone" },
  { name: "Venusaurite", category: "Mega Stone" },

  // === Misc ===
  { name: "Amulet Coin", category: "Misc" },
  { name: "Luck Incense", category: "Misc" },
  { name: "Lucky Egg", category: "Misc" },
  { name: "Lucky Punch", category: "Misc" },
  { name: "Quick Powder", category: "Misc" },
  { name: "Cleanse Tag", category: "Misc" },
  { name: "Soothe Bell", category: "Misc" },
  { name: "Exp. Share", category: "Misc" },
  { name: "Power Bracer", category: "Misc" },
  { name: "Power Belt", category: "Misc" },
  { name: "Power Lens", category: "Misc" },
  { name: "Power Band", category: "Misc" },
  { name: "Power Anklet", category: "Misc" },
  { name: "Power Weight", category: "Misc" },
  { name: "Macho Brace", category: "Misc" },
];
