window.__ITEMS_DATA__ = [
  // === Berry ===
  { name: "Berry Juice", category: "Berry", desc: "Restores 20 HP when held" },
  { name: "Ganlon Berry", category: "Berry", desc: "Raises Defense when low on HP" },
  { name: "Leppa Berry", category: "Berry", desc: "Restores 10 PP when held" },
  { name: "Liechi Berry", category: "Berry", desc: "Raises Attack when low on HP" },
  { name: "Lum Berry", category: "Berry", desc: "Cures any status condition" },
  { name: "Oran Berry", category: "Berry", desc: "Restores 10 HP when held" },
  { name: "Petaya Berry", category: "Berry", desc: "Raises Sp. Atk when low on HP" },
  { name: "Salac Berry", category: "Berry", desc: "Raises Speed when low on HP" },
  { name: "Sitrus Berry", category: "Berry", desc: "Restores 25% HP when held" },
  { name: "Starf Berry", category: "Berry", desc: "Sharply raises a random stat when low on HP" },

  // === Choice ===
  { name: "Choice Band", category: "Choice", desc: "Boosts Attack but locks into one move" },
  { name: "Choice Scarf", category: "Choice", desc: "Boosts Speed but locks into one move" },
  { name: "Choice Specs", category: "Choice", desc: "Boosts Sp. Atk but locks into one move" },

  // === Type Boost ===
  { name: "Black Belt", category: "Type Boost", desc: "Boosts Fighting-type moves" },
  { name: "Black Glasses", category: "Type Boost", desc: "Boosts Dark-type moves" },
  { name: "Charcoal", category: "Type Boost", desc: "Boosts Fire-type moves" },
  { name: "Dragon Fang", category: "Type Boost", desc: "Boosts Dragon-type moves" },
  { name: "Hard Stone", category: "Type Boost", desc: "Boosts Rock-type moves" },
  { name: "Magnet", category: "Type Boost", desc: "Boosts Electric-type moves" },
  { name: "Miracle Seed", category: "Type Boost", desc: "Boosts Grass-type moves" },
  { name: "Mystic Water", category: "Type Boost", desc: "Boosts Water-type moves" },
  { name: "Never-Melt Ice", category: "Type Boost", desc: "Boosts Ice-type moves" },
  { name: "Poison Barb", category: "Type Boost", desc: "Boosts Poison-type moves" },
  { name: "Sharp Beak", category: "Type Boost", desc: "Boosts Flying-type moves" },
  { name: "Silk Scarf", category: "Type Boost", desc: "Boosts Normal-type moves" },
  { name: "Silver Powder", category: "Type Boost", desc: "Boosts Bug-type moves" },
  { name: "Soft Sand", category: "Type Boost", desc: "Boosts Ground-type moves" },
  { name: "Spell Tag", category: "Type Boost", desc: "Boosts Ghost-type moves" },
  { name: "Twisted Spoon", category: "Type Boost", desc: "Boosts Psychic-type moves" },

  // === Evolution ===
  { name: "Everstone", category: "Evolution", desc: "Prevents evolution when held" },
  { name: "King's Rock", category: "Evolution", desc: "Causes flinching; evolves Poliwhirl/Slowpoke" },
  { name: "Metal Coat", category: "Evolution", desc: "Evolves Onix/Scyther when traded" },
  { name: "Razor Claw", category: "Evolution", desc: "Raises crit rate; evolves Sneasel" },
  { name: "Razor Fang", category: "Evolution", desc: "Causes flinching; evolves Gligar" },
  { name: "Up-Grade", category: "Evolution", desc: "Evolves Porygon when traded" },
  { name: "Dubious Disc", category: "Evolution", desc: "Evolves Porygon2 when traded" },
  { name: "Reaper Cloth", category: "Evolution", desc: "Evolves Dusclops when traded" },
  { name: "Electirizer", category: "Evolution", desc: "Evolves Electabuzz when traded" },
  { name: "Magmarizer", category: "Evolution", desc: "Evolves Magmar when traded" },
  { name: "Protector", category: "Evolution", desc: "Evolves Rhydon when traded" },
  { name: "Oval Stone", category: "Evolution", desc: "Evolves Happiny when held and leveled up" },
  { name: "Prism Scale", category: "Evolution", desc: "Evolves Feebas when traded" },
  { name: "Sachet", category: "Evolution", desc: "Evolves Spritzee when traded" },
  { name: "Whipped Dream", category: "Evolution", desc: "Evolves Swirlix when traded" },
  { name: "Ice Stone", category: "Evolution", desc: "Evolves certain Pokémon when used" },
  { name: "Fire Stone", category: "Evolution", desc: "Evolves certain Pokémon when used" },
  { name: "Thunder Stone", category: "Evolution", desc: "Evolves certain Pokémon when used" },
  { name: "Water Stone", category: "Evolution", desc: "Evolves certain Pokémon when used" },
  { name: "Leaf Stone", category: "Evolution", desc: "Evolves certain Pokémon when used" },
  { name: "Moon Stone", category: "Evolution", desc: "Evolves certain Pokémon when used" },
  { name: "Sun Stone", category: "Evolution", desc: "Evolves certain Pokémon when used" },
  { name: "Shiny Stone", category: "Evolution", desc: "Evolves certain Pokémon when used" },
  { name: "Dusk Stone", category: "Evolution", desc: "Evolves certain Pokémon when used" },
  { name: "Dawn Stone", category: "Evolution", desc: "Evolves certain Pokémon when used" },

  // === Battle ===
  { name: "Absorb Bulb", category: "Battle", desc: "Raises Sp. Atk when hit by Water moves" },
  { name: "Adrenaline Orb", category: "Battle", desc: "Raises Speed when intimidated" },
  { name: "Air Balloon", category: "Battle", desc: "Grants immunity to Ground moves" },
  { name: "Assault Vest", category: "Battle", desc: "Boosts Sp. Def but prevents status moves" },
  { name: "Big Root", category: "Battle", desc: "Boosts HP-draining moves" },
  { name: "Binding Band", category: "Battle", desc: "Boosts damage from binding moves" },
  { name: "Black Sludge", category: "Battle", desc: "Heals Poison-types; damages others" },
  { name: "Blunder Policy", category: "Battle", desc: "Sharply raises Speed when a move misses" },
  { name: "Booster Energy", category: "Battle", desc: "Activates a Paradox Pokémon's Quark Drive" },
  { name: "Bright Powder", category: "Battle", desc: "Lowers the accuracy of attacks against the holder" },
  { name: "Cell Battery", category: "Battle", desc: "Raises Attack when hit by Electric moves" },
  { name: "Clear Amulet", category: "Battle", desc: "Prevents stat reduction by opponents" },
  { name: "Covert Cloak", category: "Battle", desc: "Protects from additional effects of moves" },
  { name: "Damp Rock", category: "Battle", desc: "Extends Rain Dance duration" },
  { name: "Destiny Knot", category: "Battle", desc: "Causes infatuation when hit; passes IVs in breeding" },
  { name: "Eject Button", category: "Battle", desc: "Switches out when hit by an attack" },
  { name: "Eject Pack", category: "Battle", desc: "Switches out when stats are lowered" },
  { name: "Electric Seed", category: "Battle", desc: "Raises Defense on Electric Terrain" },
  { name: "Eviolite", category: "Battle", desc: "Boosts Defense and Sp. Def for unevolved Pokémon" },
  { name: "Expert Belt", category: "Battle", desc: "Boosts super-effective moves" },
  { name: "Flame Orb", category: "Battle", desc: "Burns the holder at the end of the turn" },
  { name: "Float Stone", category: "Battle", desc: "Halves the holder's weight" },
  { name: "Focus Band", category: "Battle", desc: "May survive a KO hit" },
  { name: "Focus Sash", category: "Battle", desc: "Survives a KO at full HP" },
  { name: "Grassy Seed", category: "Battle", desc: "Raises Defense on Grassy Terrain" },
  { name: "Grip Claw", category: "Battle", desc: "Extends binding moves duration" },
  { name: "Heat Rock", category: "Battle", desc: "Extends Sunny Day duration" },
  { name: "Heavy-Duty Boots", category: "Battle", desc: "Prevents damage from entry hazards" },
  { name: "Icy Rock", category: "Battle", desc: "Extends Hail duration" },
  { name: "Iron Ball", category: "Battle", desc: "Halves Speed; grounds Flying-types" },
  { name: "Lagging Tail", category: "Battle", desc: "Makes the holder move last" },
  { name: "Leftovers", category: "Battle", desc: "Restores 1/16 of max HP each turn" },
  { name: "Life Orb", category: "Battle", desc: "Boosts damage by 30% at a HP cost" },
  { name: "Light Clay", category: "Battle", desc: "Extends Light Screen and Reflect duration" },
  { name: "Loaded Dice", category: "Battle", desc: "Increases multi-hit move hits" },
  { name: "Luminous Moss", category: "Battle", desc: "Raises Sp. Def when hit by Water moves" },
  { name: "Mental Herb", category: "Battle", desc: "Cures infatuation, taunt, and other moves" },
  { name: "Metronome", category: "Battle", desc: "Boosts repeated moves each turn" },
  { name: "Mirror Herb", category: "Battle", desc: "Copies an opponent's stat boosts" },
  { name: "Misty Seed", category: "Battle", desc: "Raises Sp. Def on Misty Terrain" },
  { name: "Muscle Band", category: "Battle", desc: "Boosts physical move damage" },
  { name: "Power Herb", category: "Battle", desc: "Skips charging turn for moves like Solar Beam" },
  { name: "Psychic Seed", category: "Battle", desc: "Raises Sp. Def on Psychic Terrain" },
  { name: "Punching Glove", category: "Battle", desc: "Boosts punching moves; prevents contact effects" },
  { name: "Quick Claw", category: "Battle", desc: "May let the holder move first" },
  { name: "Red Card", category: "Battle", desc: "Forces the attacker to switch out" },
  { name: "Rocky Helmet", category: "Battle", desc: "Damages the attacker on contact" },
  { name: "Room Service", category: "Battle", desc: "Lowers Speed in Trick Room" },
  { name: "Safety Goggles", category: "Battle", desc: "Protects from powder moves and sand" },
  { name: "Scope Lens", category: "Battle", desc: "Raises critical hit rate" },
  { name: "Shed Shell", category: "Battle", desc: "Allows switching out of trapping moves" },
  { name: "Smoke Ball", category: "Battle", desc: "Guarantees escape from wild battles" },
  { name: "Smooth Rock", category: "Battle", desc: "Extends Sandstorm duration" },
  { name: "Snowball", category: "Battle", desc: "Raises Attack when hit by Ice moves" },
  { name: "Sticky Barb", category: "Battle", desc: "Damages holder; transfers on contact" },
  { name: "Terrain Extender", category: "Battle", desc: "Extends terrain duration" },
  { name: "Throat Spray", category: "Battle", desc: "Raises Sp. Atk after using a sound move" },
  { name: "Toxic Orb", category: "Battle", desc: "Badly poisons the holder" },
  { name: "Utility Umbrella", category: "Battle", desc: "Ignores weather effects" },
  { name: "White Herb", category: "Battle", desc: "Restores lowered stats once" },
  { name: "Wide Lens", category: "Battle", desc: "Boosts move accuracy" },
  { name: "Wise Glasses", category: "Battle", desc: "Boosts special move damage" },
  { name: "Zoom Lens", category: "Battle", desc: "Boosts accuracy when moving last" },

  // === Mega Stone ===
  { name: "Absolite", category: "Mega Stone", desc: "Mega evolves Absol" },
  { name: "Aggronite", category: "Mega Stone", desc: "Mega evolves Aggron" },
  { name: "Alakazite", category: "Mega Stone", desc: "Mega evolves Alakazam" },
  { name: "Altarianite", category: "Mega Stone", desc: "Mega evolves Altaria" },
  { name: "Ampharosite", category: "Mega Stone", desc: "Mega evolves Ampharos" },
  { name: "Audinite", category: "Mega Stone", desc: "Mega evolves Audino" },
  { name: "Banettite", category: "Mega Stone", desc: "Mega evolves Banette" },
  { name: "Beedrillite", category: "Mega Stone", desc: "Mega evolves Beedrill" },
  { name: "Blastoisinite", category: "Mega Stone", desc: "Mega evolves Blastoise" },
  { name: "Blazikenite", category: "Mega Stone", desc: "Mega evolves Blaziken" },
  { name: "Cameruptite", category: "Mega Stone", desc: "Mega evolves Camerupt" },
  { name: "Charizardite X", category: "Mega Stone", desc: "Mega evolves Charizard into X" },
  { name: "Charizardite Y", category: "Mega Stone", desc: "Mega evolves Charizard into Y" },
  { name: "Diancite", category: "Mega Stone", desc: "Mega evolves Diancie" },
  { name: "Galladite", category: "Mega Stone", desc: "Mega evolves Gallade" },
  { name: "Garchompite", category: "Mega Stone", desc: "Mega evolves Garchomp" },
  { name: "Gardevoirite", category: "Mega Stone", desc: "Mega evolves Gardevoir" },
  { name: "Gengarite", category: "Mega Stone", desc: "Mega evolves Gengar" },
  { name: "Glalitite", category: "Mega Stone", desc: "Mega evolves Glalie" },
  { name: "Gyaradosite", category: "Mega Stone", desc: "Mega evolves Gyarados" },
  { name: "Heracronite", category: "Mega Stone", desc: "Mega evolves Heracross" },
  { name: "Houndoominite", category: "Mega Stone", desc: "Mega evolves Houndoom" },
  { name: "Kangaskhanite", category: "Mega Stone", desc: "Mega evolves Kangaskhan" },
  { name: "Latiasite", category: "Mega Stone", desc: "Mega evolves Latias" },
  { name: "Latiosite", category: "Mega Stone", desc: "Mega evolves Latios" },
  { name: "Lopunnite", category: "Mega Stone", desc: "Mega evolves Lopunny" },
  { name: "Lucarionite", category: "Mega Stone", desc: "Mega evolves Lucario" },
  { name: "Manectite", category: "Mega Stone", desc: "Mega evolves Manectric" },
  { name: "Mawilite", category: "Mega Stone", desc: "Mega evolves Mawile" },
  { name: "Medichamite", category: "Mega Stone", desc: "Mega evolves Medicham" },
  { name: "Metagrossite", category: "Mega Stone", desc: "Mega evolves Metagross" },
  { name: "Mewtwonite X", category: "Mega Stone", desc: "Mega evolves Mewtwo into X" },
  { name: "Mewtwonite Y", category: "Mega Stone", desc: "Mega evolves Mewtwo into Y" },
  { name: "Pidgeotite", category: "Mega Stone", desc: "Mega evolves Pidgeot" },
  { name: "Pinsirite", category: "Mega Stone", desc: "Mega evolves Pinsir" },
  { name: "Sablenite", category: "Mega Stone", desc: "Mega evolves Sableye" },
  { name: "Salamencite", category: "Mega Stone", desc: "Mega evolves Salamence" },
  { name: "Sceptilite", category: "Mega Stone", desc: "Mega evolves Sceptile" },
  { name: "Scizorite", category: "Mega Stone", desc: "Mega evolves Scizor" },
  { name: "Sharpedonite", category: "Mega Stone", desc: "Mega evolves Sharpedo" },
  { name: "Slowbronite", category: "Mega Stone", desc: "Mega evolves Slowbro" },
  { name: "Steelixite", category: "Mega Stone", desc: "Mega evolves Steelix" },
  { name: "Swampertite", category: "Mega Stone", desc: "Mega evolves Swampert" },
  { name: "Tyranitarite", category: "Mega Stone", desc: "Mega evolves Tyranitar" },
  { name: "Venusaurite", category: "Mega Stone", desc: "Mega evolves Venusaur" },

  // === Misc ===
  { name: "Amulet Coin", category: "Misc", desc: "Doubles money after battle" },
  { name: "Luck Incense", category: "Misc", desc: "Doubles money after battle" },
  { name: "Lucky Egg", category: "Misc", desc: "Boosts EXP gained" },
  { name: "Lucky Punch", category: "Misc", desc: "Raises critical hit rate for Chansey" },
  { name: "Quick Powder", category: "Misc", desc: "Doubles Speed for Ditto" },
  { name: "Cleanse Tag", category: "Misc", desc: "Reduces wild encounter rate" },
  { name: "Soothe Bell", category: "Misc", desc: "Boosts friendship gain" },
  { name: "Exp. Share", category: "Misc", desc: "Shares EXP to the holder" },
  { name: "Power Bracer", category: "Misc", desc: "Boosts Attack EV gain; lowers Speed" },
  { name: "Power Belt", category: "Misc", desc: "Boosts Defense EV gain; lowers Speed" },
  { name: "Power Lens", category: "Misc", desc: "Boosts Sp. Atk EV gain; lowers Speed" },
  { name: "Power Band", category: "Misc", desc: "Boosts Sp. Def EV gain; lowers Speed" },
  { name: "Power Anklet", category: "Misc", desc: "Boosts Speed EV gain; lowers Speed" },
  { name: "Power Weight", category: "Misc", desc: "Boosts HP EV gain; lowers Speed" },
  { name: "Macho Brace", category: "Misc", desc: "Boosts EV gain; lowers Speed" },
];
