window.__ITEMS_DATA__ = [
  // === Berries ===
  { name: "Aguav Berry", category: "Berry", desc: "Restores HP when low but confuses if disliked" },
  { name: "Apicot Berry", category: "Berry", desc: "Raises Sp. Def when low on HP" },
  { name: "Aspear Berry", category: "Berry", desc: "Cures freeze when held" },
  { name: "Babiri Berry", category: "Berry", desc: "Weakens a super-effective Steel move" },
  { name: "Belue Berry", category: "Berry", desc: "Used for Pokéblocks and poffins" },
  { name: "Berry Juice", category: "Berry", desc: "Restores 20 HP when held" },
  { name: "Bluk Berry", category: "Berry", desc: "Used for Pokéblocks and poffins" },
  { name: "Charti Berry", category: "Berry", desc: "Weakens a super-effective Rock move" },
  { name: "Cheri Berry", category: "Berry", desc: "Cures paralysis when held" },
  { name: "Chesto Berry", category: "Berry", desc: "Cures sleep when held" },
  { name: "Chilan Berry", category: "Berry", desc: "Weakens a Normal move" },
  { name: "Chople Berry", category: "Berry", desc: "Weakens a super-effective Fighting move" },
  { name: "Coba Berry", category: "Berry", desc: "Weakens a super-effective Flying move" },
  { name: "Colbur Berry", category: "Berry", desc: "Weakens a super-effective Dark move" },
  { name: "Cornn Berry", category: "Berry", desc: "Used for Pokéblocks and poffins" },
  { name: "Custap Berry", category: "Berry", desc: "Lets the holder move first in a pinch" },
  { name: "Durin Berry", category: "Berry", desc: "Used for Pokéblocks and poffins" },
  { name: "Enigma Berry", category: "Berry", desc: "Restores HP if hit by a super-effective move" },
  { name: "Figy Berry", category: "Berry", desc: "Restores HP when low but confuses if disliked" },
  { name: "Ganlon Berry", category: "Berry", desc: "Raises Defense when low on HP" },
  { name: "Grepa Berry", category: "Berry", desc: "Lowers Sp. Def EVs, raises friendship" },
  { name: "Haban Berry", category: "Berry", desc: "Weakens a super-effective Dragon move" },
  { name: "Hondew Berry", category: "Berry", desc: "Lowers Sp. Atk EVs, raises friendship" },
  { name: "Iapapa Berry", category: "Berry", desc: "Restores HP when low but confuses if disliked" },
  { name: "Jaboca Berry", category: "Berry", desc: "Damages attacker on physical contact if consumed" },
  { name: "Kasib Berry", category: "Berry", desc: "Weakens a super-effective Ghost move" },
  { name: "Kebia Berry", category: "Berry", desc: "Weakens a super-effective Poison move" },
  { name: "Kee Berry", category: "Berry", desc: "Raises Defense when hit by a physical move" },
  { name: "Kelpsy Berry", category: "Berry", desc: "Lowers Attack EVs, raises friendship" },
  { name: "Lansat Berry", category: "Berry", desc: "Raises critical-hit ratio when low on HP" },
  { name: "Leppa Berry", category: "Berry", desc: "Restores 10 PP when held" },
  { name: "Liechi Berry", category: "Berry", desc: "Raises Attack when low on HP" },
  { name: "Lum Berry", category: "Berry", desc: "Cures any status condition" },
  { name: "Mago Berry", category: "Berry", desc: "Restores HP when low but confuses if disliked" },
  { name: "Magost Berry", category: "Berry", desc: "Used for Pokéblocks and poffins" },
  { name: "Maranga Berry", category: "Berry", desc: "Raises Sp. Def when hit by a special move" },
  { name: "Micle Berry", category: "Berry", desc: "Raises accuracy on one move when low on HP" },
  { name: "Nanab Berry", category: "Berry", desc: "Used for Pokéblocks and poffins" },
  { name: "Nomel Berry", category: "Berry", desc: "Used for Pokéblocks and poffins" },
  { name: "Occa Berry", category: "Berry", desc: "Weakens a super-effective Fire move" },
  { name: "Oran Berry", category: "Berry", desc: "Restores 10 HP when held" },
  { name: "Pamtre Berry", category: "Berry", desc: "Used for Pokéblocks and poffins" },
  { name: "Passho Berry", category: "Berry", desc: "Weakens a super-effective Water move" },
  { name: "Payapa Berry", category: "Berry", desc: "Weakens a super-effective Psychic move" },
  { name: "Pecha Berry", category: "Berry", desc: "Cures poison when held" },
  { name: "Persim Berry", category: "Berry", desc: "Cures confusion when held" },
  { name: "Petaya Berry", category: "Berry", desc: "Raises Sp. Atk when low on HP" },
  { name: "Pinap Berry", category: "Berry", desc: "Used for Pokéblocks and poffins" },
  { name: "Pomeg Berry", category: "Berry", desc: "Lowers HP EVs, raises friendship" },
  { name: "Qualot Berry", category: "Berry", desc: "Lowers Defense EVs, raises friendship" },
  { name: "Rabuta Berry", category: "Berry", desc: "Used for Pokéblocks and poffins" },
  { name: "Rawst Berry", category: "Berry", desc: "Cures burn when held" },
  { name: "Razz Berry", category: "Berry", desc: "Used for Pokéblocks and poffins" },
  { name: "Rindo Berry", category: "Berry", desc: "Weakens a super-effective Grass move" },
  { name: "Roseli Berry", category: "Berry", desc: "Weakens a super-effective Fairy move" },
  { name: "Rowap Berry", category: "Berry", desc: "Damages attacker on special contact if consumed" },
  { name: "Salac Berry", category: "Berry", desc: "Raises Speed when low on HP" },
  { name: "Shuca Berry", category: "Berry", desc: "Weakens a super-effective Ground move" },
  { name: "Sitrus Berry", category: "Berry", desc: "Restores 25% HP when held" },
  { name: "Spelon Berry", category: "Berry", desc: "Used for Pokéblocks and poffins" },
  { name: "Starf Berry", category: "Berry", desc: "Sharply raises a random stat when low on HP" },
  { name: "Tanga Berry", category: "Berry", desc: "Weakens a super-effective Bug move" },
  { name: "Tamato Berry", category: "Berry", desc: "Lowers Speed EVs, raises friendship" },
  { name: "Wacan Berry", category: "Berry", desc: "Weakens a super-effective Electric move" },
  { name: "Watmel Berry", category: "Berry", desc: "Used for Pokéblocks and poffins" },
  { name: "Wepear Berry", category: "Berry", desc: "Used for Pokéblocks and poffins" },
  { name: "Wiki Berry", category: "Berry", desc: "Restores HP when low but confuses if disliked" },
  { name: "Yache Berry", category: "Berry", desc: "Weakens a super-effective Ice move" },

  // === Choice ===
  { name: "Choice Band", category: "Choice", desc: "Boosts Attack by 50% but locks into one move" },
  { name: "Choice Scarf", category: "Choice", desc: "Boosts Speed by 50% but locks into one move" },
  { name: "Choice Specs", category: "Choice", desc: "Boosts Sp. Atk by 50% but locks into one move" },

  // === Type Boost ===
  { name: "Black Belt", category: "Type Boost", desc: "Boosts Fighting-type moves by 20%" },
  { name: "Black Glasses", category: "Type Boost", desc: "Boosts Dark-type moves by 20%" },
  { name: "Charcoal", category: "Type Boost", desc: "Boosts Fire-type moves by 20%" },
  { name: "Dragon Fang", category: "Type Boost", desc: "Boosts Dragon-type moves by 20%" },
  { name: "Hard Stone", category: "Type Boost", desc: "Boosts Rock-type moves by 20%" },
  { name: "Magnet", category: "Type Boost", desc: "Boosts Electric-type moves by 20%" },
  { name: "Metal Coat", category: "Type Boost", desc: "Boosts Steel-type moves by 20%; evolves Onix/Scyther when traded" },
  { name: "Miracle Seed", category: "Type Boost", desc: "Boosts Grass-type moves by 20%" },
  { name: "Mystic Water", category: "Type Boost", desc: "Boosts Water-type moves by 20%" },
  { name: "Never-Melt Ice", category: "Type Boost", desc: "Boosts Ice-type moves by 20%" },
  { name: "Pixie Plate", category: "Type Boost", desc: "Boosts Fairy-type moves by 20%" },
  { name: "Poison Barb", category: "Type Boost", desc: "Boosts Poison-type moves by 20%" },
  { name: "Sharp Beak", category: "Type Boost", desc: "Boosts Flying-type moves by 20%" },
  { name: "Silk Scarf", category: "Type Boost", desc: "Boosts Normal-type moves by 20%" },
  { name: "Silver Powder", category: "Type Boost", desc: "Boosts Bug-type moves by 20%" },
  { name: "Soft Sand", category: "Type Boost", desc: "Boosts Ground-type moves by 20%" },
  { name: "Spell Tag", category: "Type Boost", desc: "Boosts Ghost-type moves by 20%" },
  { name: "Twisted Spoon", category: "Type Boost", desc: "Boosts Psychic-type moves by 20%" },

  // === Plates ===
  { name: "Draco Plate", category: "Type Boost", desc: "Boosts Dragon-type moves by 20%; changes Arceus to Dragon" },
  { name: "Dread Plate", category: "Type Boost", desc: "Boosts Dark-type moves by 20%; changes Arceus to Dark" },
  { name: "Earth Plate", category: "Type Boost", desc: "Boosts Ground-type moves by 20%; changes Arceus to Ground" },
  { name: "Fist Plate", category: "Type Boost", desc: "Boosts Fighting-type moves by 20%; changes Arceus to Fighting" },
  { name: "Flame Plate", category: "Type Boost", desc: "Boosts Fire-type moves by 20%; changes Arceus to Fire" },
  { name: "Icicle Plate", category: "Type Boost", desc: "Boosts Ice-type moves by 20%; changes Arceus to Ice" },
  { name: "Insect Plate", category: "Type Boost", desc: "Boosts Bug-type moves by 20%; changes Arceus to Bug" },
  { name: "Iron Plate", category: "Type Boost", desc: "Boosts Steel-type moves by 20%; changes Arceus to Steel" },
  { name: "Meadow Plate", category: "Type Boost", desc: "Boosts Grass-type moves by 20%; changes Arceus to Grass" },
  { name: "Mind Plate", category: "Type Boost", desc: "Boosts Psychic-type moves by 20%; changes Arceus to Psychic" },
  { name: "Sky Plate", category: "Type Boost", desc: "Boosts Flying-type moves by 20%; changes Arceus to Flying" },
  { name: "Splash Plate", category: "Type Boost", desc: "Boosts Water-type moves by 20%; changes Arceus to Water" },
  { name: "Spooky Plate", category: "Type Boost", desc: "Boosts Ghost-type moves by 20%; changes Arceus to Ghost" },
  { name: "Stone Plate", category: "Type Boost", desc: "Boosts Rock-type moves by 20%; changes Arceus to Rock" },
  { name: "Toxic Plate", category: "Type Boost", desc: "Boosts Poison-type moves by 20%; changes Arceus to Poison" },
  { name: "Zap Plate", category: "Type Boost", desc: "Boosts Electric-type moves by 20%; changes Arceus to Electric" },

  // === Evolution ===
  { name: "Auspicious Armor", category: "Evolution", desc: "Evolves Charcadet into Armarouge" },
  { name: "Dawn Stone", category: "Evolution", desc: "Evolves Kirlia and Snorunt" },
  { name: "Dragon Scale", category: "Evolution", desc: "Evolves Seadra when traded" },
  { name: "Dubious Disc", category: "Evolution", desc: "Evolves Porygon2 when traded" },
  { name: "Dusk Stone", category: "Evolution", desc: "Evolves Murkrow, Misdreavus, Lampent, and Doublade" },
  { name: "Electirizer", category: "Evolution", desc: "Evolves Electabuzz when traded" },
  { name: "Everstone", category: "Evolution", desc: "Prevents evolution when held" },
  { name: "Fire Stone", category: "Evolution", desc: "Evolves Vulpix, Growlithe, Eevee, and Pansear" },
  { name: "Ice Stone", category: "Evolution", desc: "Evolves Alolan Vulpix, Alolan Sandshrew, Eevee, and Galarian Darumaka" },
  { name: "King's Rock", category: "Evolution", desc: "Evolves Poliwhirl and Slowpoke when traded; may cause flinching" },
  { name: "Leaf Stone", category: "Evolution", desc: "Evolves Gloom, Weepinbell, Exeggcute, Nuzleaf, and Pansage" },
  { name: "Magmarizer", category: "Evolution", desc: "Evolves Magmar when traded" },
  { name: "Malicious Armor", category: "Evolution", desc: "Evolves Charcadet into Ceruledge" },
  { name: "Moon Stone", category: "Evolution", desc: "Evolves Nidorina, Nidorino, Clefairy, Jigglypuff, Skitty, and Munna" },
  { name: "Oval Stone", category: "Evolution", desc: "Evolves Happiny when held and leveled up" },
  { name: "Prism Scale", category: "Evolution", desc: "Evolves Feebas when traded" },
  { name: "Protector", category: "Evolution", desc: "Evolves Rhydon when traded" },
  { name: "Razor Claw", category: "Evolution", desc: "Evolves Sneasel when held and leveled up; raises critical hit ratio" },
  { name: "Razor Fang", category: "Evolution", desc: "Evolves Gligar when held and leveled up; may cause flinching" },
  { name: "Reaper Cloth", category: "Evolution", desc: "Evolves Dusclops when traded" },
  { name: "Sachet", category: "Evolution", desc: "Evolves Spritzee when traded" },
  { name: "Shiny Stone", category: "Evolution", desc: "Evolves Togetic, Roselia, Minccino, and Floette" },
  { name: "Sun Stone", category: "Evolution", desc: "Evolves Gloom, Sunkern, Cottonee, Petilil, and Helioptile" },
  { name: "Thunder Stone", category: "Evolution", desc: "Evolves Pikachu, Eevee, and Eelektrik" },
  { name: "Up-Grade", category: "Evolution", desc: "Evolves Porygon when traded" },
  { name: "Water Stone", category: "Evolution", desc: "Evolves Poliwhirl, Shellder, Staryu, Eevee, Lombre, and Panpour" },
  { name: "Whipped Dream", category: "Evolution", desc: "Evolves Swirlix when traded" },

  // === Battle ===
  { name: "Ability Shield", category: "Battle", desc: "Prevents the holder's ability from being changed" },
  { name: "Absorb Bulb", category: "Battle", desc: "Raises Sp. Atk when hit by a Water move" },
  { name: "Adrenaline Orb", category: "Battle", desc: "Raises Speed when intimidated" },
  { name: "Air Balloon", category: "Battle", desc: "Grants immunity to Ground moves; pops when hit" },
  { name: "Assault Vest", category: "Battle", desc: "Raises Sp. Def by 50% but prevents status moves" },
  { name: "Big Root", category: "Battle", desc: "Boosts HP-draining moves by 30%" },
  { name: "Binding Band", category: "Battle", desc: "Increases binding move damage from 1/8 to 1/6 max HP" },
  { name: "Black Sludge", category: "Battle", desc: "Heals Poison-types each turn; damages others" },
  { name: "Blunder Policy", category: "Battle", desc: "Sharply raises Speed when a move misses" },
  { name: "Booster Energy", category: "Battle", desc: "Activates Quark Drive or Protosynthesis" },
  { name: "Bright Powder", category: "Battle", desc: "Lowers accuracy of attacks against the holder by 10%" },
  { name: "Cell Battery", category: "Battle", desc: "Raises Attack when hit by an Electric move" },
  { name: "Clear Amulet", category: "Battle", desc: "Prevents stat reduction by opponents" },
  { name: "Covert Cloak", category: "Battle", desc: "Protects from additional effects of moves" },
  { name: "Damp Rock", category: "Battle", desc: "Extends Rain Dance to 8 turns" },
  { name: "Destiny Knot", category: "Battle", desc: "Infatuates attacker on contact; passes 5 IVs in breeding" },
  { name: "Eject Button", category: "Battle", desc: "Switches out when hit by an attack" },
  { name: "Eject Pack", category: "Battle", desc: "Switches out when stats are lowered" },
  { name: "Electric Seed", category: "Battle", desc: "Raises Defense on Electric Terrain" },
  { name: "Eviolite", category: "Battle", desc: "Boosts Defense and Sp. Def by 50% for unevolved Pokémon" },
  { name: "Expert Belt", category: "Battle", desc: "Boosts super-effective moves by 20%" },
  { name: "Flame Orb", category: "Battle", desc: "Burns the holder at the end of the turn" },
  { name: "Float Stone", category: "Battle", desc: "Halves the holder's weight" },
  { name: "Focus Band", category: "Battle", desc: "10% chance to survive a KO hit" },
  { name: "Focus Sash", category: "Battle", desc: "Survives a KO hit at full HP" },
  { name: "Grassy Seed", category: "Battle", desc: "Raises Defense on Grassy Terrain" },
  { name: "Grip Claw", category: "Battle", desc: "Extends binding moves to 7 turns" },
  { name: "Heat Rock", category: "Battle", desc: "Extends Sunny Day to 8 turns" },
  { name: "Heavy-Duty Boots", category: "Battle", desc: "Prevents damage from entry hazards" },
  { name: "Icy Rock", category: "Battle", desc: "Extends Hail/Snow to 8 turns" },
  { name: "Iron Ball", category: "Battle", desc: "Halves Speed; grounds Flying-types" },
  { name: "Lagging Tail", category: "Battle", desc: "Makes the holder move last" },
  { name: "Leftovers", category: "Battle", desc: "Restores 1/16 of max HP each turn" },
  { name: "Life Orb", category: "Battle", desc: "Boosts damage by 30% at a cost of 10% HP per attack" },
  { name: "Light Clay", category: "Battle", desc: "Extends Light Screen and Reflect to 8 turns" },
  { name: "Loaded Dice", category: "Battle", desc: "Increases multi-hit moves to at least 4 hits" },
  { name: "Luminous Moss", category: "Battle", desc: "Raises Sp. Def when hit by a Water move" },
  { name: "Mental Herb", category: "Battle", desc: "Cures infatuation, taunt, encore, disable, and heal block" },
  { name: "Metronome", category: "Battle", desc: "Boosts repeated moves each turn up to 2x" },
  { name: "Mirror Herb", category: "Battle", desc: "Copies an opponent's stat boosts once" },
  { name: "Misty Seed", category: "Battle", desc: "Raises Sp. Def on Misty Terrain" },
  { name: "Muscle Band", category: "Battle", desc: "Boosts physical move damage by 10%" },
  { name: "Power Herb", category: "Battle", desc: "Skips charging turn for moves like Solar Beam" },
  { name: "Protective Pads", category: "Battle", desc: "Protects from contact effects like Iron Barbs" },
  { name: "Psychic Seed", category: "Battle", desc: "Raises Sp. Def on Psychic Terrain" },
  { name: "Punching Glove", category: "Battle", desc: "Boosts punching moves by 10%; prevents contact effects" },
  { name: "Quick Claw", category: "Battle", desc: "20% chance to move first regardless of Speed" },
  { name: "Red Card", category: "Battle", desc: "Forces the attacker to switch out once" },
  { name: "Ring Target", category: "Battle", desc: "Holder loses type immunities" },
  { name: "Rocky Helmet", category: "Battle", desc: "Damages attacker by 1/6 max HP on contact" },
  { name: "Room Service", category: "Battle", desc: "Lowers Speed in Trick Room" },
  { name: "Safety Goggles", category: "Battle", desc: "Protects from weather damage and powder moves" },
  { name: "Scope Lens", category: "Battle", desc: "Boosts critical hit ratio by 1 stage" },
  { name: "Shell Bell", category: "Battle", desc: "Restores 1/8 of damage dealt as HP" },
  { name: "Shed Shell", category: "Battle", desc: "Allows the holder to switch out freely" },
  { name: "Smoke Ball", category: "Battle", desc: "Guarantees escape from wild battles" },
  { name: "Smooth Rock", category: "Battle", desc: "Extends Sandstorm to 8 turns" },
  { name: "Snowball", category: "Battle", desc: "Raises Attack when hit by an Ice move" },
  { name: "Sticky Barb", category: "Battle", desc: "Damages holder each turn; transfers on contact" },
  { name: "Terrain Extender", category: "Battle", desc: "Extends terrain to 8 turns" },
  { name: "Throat Spray", category: "Battle", desc: "Raises Sp. Atk after using a sound move" },
  { name: "Toxic Orb", category: "Battle", desc: "Badly poisons the holder" },
  { name: "Utility Umbrella", category: "Battle", desc: "Holder ignores weather effects" },
  { name: "Weakness Policy", category: "Battle", desc: "Sharply raises Attack and Sp. Atk when hit super-effectively" },
  { name: "White Herb", category: "Battle", desc: "Restores lowered stats once" },
  { name: "Wide Lens", category: "Battle", desc: "Boosts move accuracy by 10%" },
  { name: "Wise Glasses", category: "Battle", desc: "Boosts special move damage by 10%" },
  { name: "Zoom Lens", category: "Battle", desc: "Boosts accuracy by 20% when moving last" },

  // === Species-Specific ===
  { name: "Adamant Orb", category: "Battle", desc: "Boosts Dialga's Dragon and Steel moves by 20%" },
  { name: "Deep Sea Scale", category: "Battle", desc: "Doubles Clamperl's Sp. Def; evolves Clamperl when traded" },
  { name: "Deep Sea Tooth", category: "Battle", desc: "Doubles Clamperl's Sp. Atk; evolves Clamperl when traded" },
  { name: "Griseous Core", category: "Battle", desc: "Boosts Giratina's Dragon and Ghost moves; transforms Origin Forme" },
  { name: "Griseous Orb", category: "Battle", desc: "Boosts Giratina's Dragon and Ghost moves; transforms Origin Forme" },
  { name: "Light Ball", category: "Battle", desc: "Doubles Pikachu's Attack and Sp. Atk" },
  { name: "Lustrous Orb", category: "Battle", desc: "Boosts Palkia's Dragon and Water moves by 20%" },
  { name: "Rusty Sword", category: "Battle", desc: "Transforms Zacian to Crowned Sword; boosts Attack" },
  { name: "Rusty Shield", category: "Battle", desc: "Transforms Zamazenta to Crowned Shield; boosts Defense" },
  { name: "Soul Dew", category: "Battle", desc: "Boosts Latios/Latias's Sp. Atk and Sp. Def by 50%" },
  { name: "Thick Club", category: "Battle", desc: "Doubles Cubone and Marowak's Attack" },

  // === Mega Stone ===
  { name: "Absolite", category: "Mega Stone", desc: "Mega evolves Absol" },
  { name: "Aerodactylite", category: "Mega Stone", desc: "Mega evolves Aerodactyl" },
  { name: "Aggronite", category: "Mega Stone", desc: "Mega evolves Aggron" },
  { name: "Alakazite", category: "Mega Stone", desc: "Mega evolves Alakazam" },
  { name: "Altarianite", category: "Mega Stone", desc: "Mega evolves Altaria" },
  { name: "Ampharosite", category: "Mega Stone", desc: "Mega evolves Ampharos" },
  { name: "Audinite", category: "Mega Stone", desc: "Mega evolves Audino" },
  { name: "Banettite", category: "Mega Stone", desc: "Mega evolves Banette" },
  { name: "Beedrillite", category: "Mega Stone", desc: "Mega evolves Beedrill" },
  { name: "Blastoisinite", category: "Mega Stone", desc: "Mega evolves Blastoise" },
  { name: "Blazikenite", category: "Mega Stone", desc: "Mega evolves Blaziken" },
  { name: "Cameruptite", category: "Mega Stone", desc: "Mega evolves Camerupt" },
  { name: "Charizardite X", category: "Mega Stone", desc: "Mega evolves Charizard into Mega Charizard X" },
  { name: "Charizardite Y", category: "Mega Stone", desc: "Mega evolves Charizard into Mega Charizard Y" },
  { name: "Diancite", category: "Mega Stone", desc: "Mega evolves Diancie" },
  { name: "Galladite", category: "Mega Stone", desc: "Mega evolves Gallade" },
  { name: "Garchompite", category: "Mega Stone", desc: "Mega evolves Garchomp" },
  { name: "Gardevoirite", category: "Mega Stone", desc: "Mega evolves Gardevoir" },
  { name: "Gengarite", category: "Mega Stone", desc: "Mega evolves Gengar" },
  { name: "Glalitite", category: "Mega Stone", desc: "Mega evolves Glalie" },
  { name: "Gyaradosite", category: "Mega Stone", desc: "Mega evolves Gyarados" },
  { name: "Heracronite", category: "Mega Stone", desc: "Mega evolves Heracross" },
  { name: "Houndoominite", category: "Mega Stone", desc: "Mega evolves Houndoom" },
  { name: "Kangaskhanite", category: "Mega Stone", desc: "Mega evolves Kangaskhan" },
  { name: "Latiasite", category: "Mega Stone", desc: "Mega evolves Latias" },
  { name: "Latiosite", category: "Mega Stone", desc: "Mega evolves Latios" },
  { name: "Lopunnite", category: "Mega Stone", desc: "Mega evolves Lopunny" },
  { name: "Lucarionite", category: "Mega Stone", desc: "Mega evolves Lucario" },
  { name: "Manectite", category: "Mega Stone", desc: "Mega evolves Manectric" },
  { name: "Mawilite", category: "Mega Stone", desc: "Mega evolves Mawile" },
  { name: "Medichamite", category: "Mega Stone", desc: "Mega evolves Medicham" },
  { name: "Metagrossite", category: "Mega Stone", desc: "Mega evolves Metagross" },
  { name: "Mewtwonite X", category: "Mega Stone", desc: "Mega evolves Mewtwo into Mega Mewtwo X" },
  { name: "Mewtwonite Y", category: "Mega Stone", desc: "Mega evolves Mewtwo into Mega Mewtwo Y" },
  { name: "Pidgeotite", category: "Mega Stone", desc: "Mega evolves Pidgeot" },
  { name: "Pinsirite", category: "Mega Stone", desc: "Mega evolves Pinsir" },
  { name: "Sablenite", category: "Mega Stone", desc: "Mega evolves Sableye" },
  { name: "Salamencite", category: "Mega Stone", desc: "Mega evolves Salamence" },
  { name: "Sceptilite", category: "Mega Stone", desc: "Mega evolves Sceptile" },
  { name: "Scizorite", category: "Mega Stone", desc: "Mega evolves Scizor" },
  { name: "Sharpedonite", category: "Mega Stone", desc: "Mega evolves Sharpedo" },
  { name: "Slowbronite", category: "Mega Stone", desc: "Mega evolves Slowbro" },
  { name: "Steelixite", category: "Mega Stone", desc: "Mega evolves Steelix" },
  { name: "Swampertite", category: "Mega Stone", desc: "Mega evolves Swampert" },
  { name: "Tyranitarite", category: "Mega Stone", desc: "Mega evolves Tyranitar" },
  { name: "Venusaurite", category: "Mega Stone", desc: "Mega evolves Venusaur" },

  // === Misc ===
  { name: "Amulet Coin", category: "Misc", desc: "Doubles prize money" },
  { name: "Cleanse Tag", category: "Misc", desc: "Lowers wild encounter rate" },
  { name: "Exp. Share", category: "Misc", desc: "Shares experience with party" },
  { name: "Luck Incense", category: "Misc", desc: "Doubles prize money" },
  { name: "Lucky Egg", category: "Misc", desc: "Boosts experience gained by 50%" },
  { name: "Lucky Punch", category: "Misc", desc: "Raises Chansey's critical-hit ratio" },
  { name: "Macho Brace", category: "Misc", desc: "Doubles EV gain but halves Speed" },
  { name: "Power Anklet", category: "Misc", desc: "Adds 8 Speed EVs but halves Speed in battle" },
  { name: "Power Band", category: "Misc", desc: "Adds 8 Sp. Def EVs but halves Speed in battle" },
  { name: "Power Belt", category: "Misc", desc: "Adds 8 Defense EVs but halves Speed in battle" },
  { name: "Power Bracer", category: "Misc", desc: "Adds 8 Attack EVs but halves Speed in battle" },
  { name: "Power Lens", category: "Misc", desc: "Adds 8 Sp. Atk EVs but halves Speed in battle" },
  { name: "Power Weight", category: "Misc", desc: "Adds 8 HP EVs but halves Speed in battle" },
  { name: "Quick Powder", category: "Misc", desc: "Doubles Ditto's Speed" },
  { name: "Soothe Bell", category: "Misc", desc: "Boosts friendship gain" },
];
